# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='/static/img/cogorange.png', upload_to=''),
        ),
    ]
